# -*- coding: utf-8 -*-
"""задача 1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13U-NlDeND60MZhxTPWK5-6yNimiFtWvy

f-строки
"""

name = "Пушкин"
value = 9.67
print(f"Индекс озеленения территории {name} равен {value}%")  # такой формат строк, позволяет добавлять в него динамические значения

"""##### **Задача 1** """

class GreenZoneIndex:

    
    def __init__(self, territory_name, territory_area, green_zones):
        """
        :param territory_name: Название территории
        :param territory_area: Площадь территории
        :param green_zones: Список площадей парков
        """
        # TODO все аргументы конструктора записать в атрибуты экземпляра класса
        self.territory_name = territory_name
        self.territory_area = territory_area
        self.green_zones = green_zones

        self.green_index = self.calculate_green_index()  # индекс озеленения

        # TODO посчитать индекс озеленения с помощью метода calculate_green_index

        

    def calculate_green_index(self):
        """
        Метод для вычисления индекса озеленения.

        Индекс рассчитывается как отношение площади всех парков к площади территории
        """

        # TODO посчитать индекс озеленения с атрибутов экземпляра класса

        green_index = (sum(self.green_zones) / self.territory_area) * 100

        return round(green_index, 2)
    

    def __str__(self):
        s = f"Я ЭКЗЕМПЛЯР КЛАССА GreenZoneIndex. МОЁ ИМЯ - {self.territory_name}, МОЯ ПЛОЩАДЬ - {self.territory_area}, МОИ ЗОНЫ - СПИСОК {self.green_zones}, МОЙ green_index - {self.green_index}"

        return s


    def __repr__(self):
      return self.__str__()

territory_name = "Пушкин"
territory_area = 28676
green_zones = [302, 487, 420, 325, 471, 363, 404]

# Создать экземпряр класса и с помощью его атрибутов распечатать индекс озеленения в процентах до 2 знака после запятой. 
pushkin = GreenZoneIndex(territory_name, territory_area, green_zones)
print(f"Индекс озеленения территории {pushkin.territory_name} равен {pushkin.green_index}%")